- name: task:agent
  color: 5319e7
  description: Orchestrator triggers agents
- name: agent:engineer
  color: 0e8a16
  description: Engineer agent PRs
- name: agent:growth
  color: 1d76db
  description: Growth agent PRs
- name: proposal:ceo
  color: b60205
  description: CEO proposals waiting approval
