name: Agent Task
description: Orchestrator + Agents starten für diese Aufgabe
labels: ["task:agent"]
body:
  - type: input
    id: goal
    attributes:
      label: Ziel (SMART)
      placeholder: Was soll in PR(s) landen?
  - type: textarea
    id: context
    attributes:
      label: Kontext/Constraints
  - type: textarea
    id: acceptance
    attributes:
      label: Akzeptanzkriterien/Eval
