name: Agent Task
description: Orchestrator + Agents starten für diese Aufgabe
labels: ["task:agent"]
body:
  - type: input
    id: goal
    attributes:
      label: Ziel (SMART)
      placeholder: Was soll in PR(s) landen?
  - type: textarea
    id: context
    attributes:
      label: Kontext/Constraints
      placeholder: Links, Dateien, Risiken
  - type: textarea
    id: acceptance
    attributes:
      label: Akzeptanzkriterien/Eval
      placeholder: Nachweis, Tests, Definition of Done
