name: Agent Growth
on:
  repository_dispatch:
    types: [agent-growth]
  workflow_dispatch:
    inputs:
      issue_number: { description: Issue #, required: true }
      plan_path:    { description: Plan path, required: false }
      issue_title:  { description: Issue title, required: false }
concurrency:
  group: agent-growth-${{ github.event.client_payload.issue_number || inputs.issue_number || github.run_id }}
  cancel-in-progress: false
permissions:
  contents: write
  pull-requests: write
jobs:
  growth:
    runs-on: ubuntu-latest
    env:
      ISSUE_NUMBER: ${{ github.event.client_payload.issue_number || inputs.issue_number || '0' }}
      PLAN_PATH:    ${{ github.event.client_payload.plan_path    || inputs.plan_path    || '' }}
      ISSUE_TITLE:  ${{ github.event.client_payload.issue_title  || inputs.issue_title  || '' }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Add deterministic outreach drafts (idempotent)
        run: |
          mkdir -p drafts/outreach reports/agent_runs
          if [ ! -f drafts/outreach/template.md ]; then
            cat > drafts/outreach/template.md << 'MD'
# Outreach Draft (v1)

**Zielkunden:** B2B-Leads aus Parsing-Pipeline  
**CTA:** 15-min Call oder 2-Min-Demo

## Version A (Kurz)
Hi {{first_name}}, wir haben ein kleines Tool gebaut, das {{pain_point}} in {{X}} Minuten automatisiert.
Darf ich dir in 2 Screens zeigen, wie?

## Version B (Value-first)
Hey {{first_name}}, mir ist bei {{company}} aufgefallen: {{trigger}}.
Wir haben {{benefit}} mit {{proof}} erreicht. Soll ich dir eine 2-Min-Demo schicken?

— {{sender}}
MD
          fi
          if [ ! -f drafts/README.md ]; then
            cat > drafts/README.md << 'MD'
# Drafts
Deterministische Vorlagen. Keine PII/Secrets. Änderungen per PR.
MD
          fi
          ACK="reports/agent_runs/growth-issue-${ISSUE_NUMBER}.md"
          if [ ! -f "$ACK" ]; then
            echo "# Growth run for Issue #${ISSUE_NUMBER}" > "$ACK"
            echo "Plan: ${PLAN_PATH}" >> "$ACK"
          fi
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "feat(growth): outreach drafts v1"
          branch: "agent/growth/issue-${{ env.ISSUE_NUMBER }}"
          title: "Growth: Outreach-Drafts für #${{ env.ISSUE_NUMBER }}"
          body: |
            Basierend auf Plan: `${{ env.PLAN_PATH }}`
            - `drafts/outreach/template.md` (idempotent)
            - `drafts/README.md` (idempotent)
            - Ack-Datei für Nachvollziehbarkeit
          labels: agent:growth, ready-for-review
          signoff: true
          delete-branch: true
