name: Agent Engineer
on:
  repository_dispatch:
    types: [agent-engineer]
  workflow_dispatch:
    inputs:
      issue_number: { description: Issue #, required: true }
      plan_path:    { description: Plan path, required: false }
      issue_title:  { description: Issue title, required: false }
concurrency:
  group: agent-engineer-${{ github.event.client_payload.issue_number || inputs.issue_number || github.run_id }}
  cancel-in-progress: false
permissions:
  contents: write
  pull-requests: write
jobs:
  engineer:
    runs-on: ubuntu-latest
    env:
      ISSUE_NUMBER: ${{ github.event.client_payload.issue_number || inputs.issue_number || '0' }}
      PLAN_PATH:    ${{ github.event.client_payload.plan_path    || inputs.plan_path    || '' }}
      ISSUE_TITLE:  ${{ github.event.client_payload.issue_title  || inputs.issue_title  || '' }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Ensure deterministic test scaffolding (idempotent)
        run: |
          mkdir -p tests
          if [ ! -f tests/test_normalize_leads.py ]; then
            cat > tests/test_normalize_leads.py << 'PY'
import json, subprocess
def run_csv(inp):
  p = subprocess.run(["python","scripts/normalize_leads.py"], input=inp.encode(), capture_output=True)
  assert p.returncode == 0, p.stderr.decode()
  return json.loads(p.stdout.decode())
def test_basic_normalization():
  csv = "Name , Email \n Alice , alice@example.com \n"
  out = run_csv(csv)
  assert isinstance(out, list) and len(out) >= 1
PY
          fi
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Quick local test (non-blocking)
        continue-on-error: true
        run: pytest -q || true
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "test(engineer): add/ensure smoke tests for normalize_leads"
          branch: "agent/engineer/issue-${{ env.ISSUE_NUMBER }}"
          title: "Engineer: Tests/Scaffolding für #${{ env.ISSUE_NUMBER }}"
          body: |
            Basierend auf Plan: `${{ env.PLAN_PATH }}`
            - Smoke-Test für `scripts/normalize_leads.py` (idempotent)
          labels: agent:engineer, ready-for-review
          signoff: true
          delete-branch: true
