name: Agent Engineer

on:
  repository_dispatch:
    types: [agent-engineer]

permissions:
  contents: write
  pull-requests: write

jobs:
  engineer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read payload
        run: |
          echo "ISSUE_NUMBER=${{ github.event.client_payload.issue_number }}" >> $GITHUB_ENV
          echo "PLAN_PATH=${{ github.event.client_payload.plan_path }}" >> $GITHUB_ENV
          echo "ISSUE_TITLE=${{ github.event.client_payload.issue_title }}" >> $GITHUB_ENV

      - name: Ensure deterministic test scaffolding (idempotent)
        run: |
          mkdir -p tests
          if [ ! -f tests/test_normalize_leads.py ]; then
            cat > tests/test_normalize_leads.py << 'PY'
import json, subprocess
def run_csv(inp):
  p = subprocess.run(["python","scripts/normalize_leads.py"], input=inp.encode(), capture_output=True)
  assert p.returncode == 0, p.stderr.decode()
  return json.loads(p.stdout.decode())
def test_basic_normalization():
  csv = "Name , Email \n Alice , alice@example.com \n"
  out = run_csv(csv)
  assert isinstance(out, list) and len(out) >= 1
PY
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: Quick local test (non-blocking)
        continue-on-error: true
        run: |
          pytest -q || true

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "test(engineer): add/ensure smoke tests for normalize_leads"
          branch: "agent/engineer/issue-${{ env.ISSUE_NUMBER }}"
          title: "Engineer: Tests/Scaffolding für #${{ env.ISSUE_NUMBER }}"
          body: |
            Basierend auf Plan: `${{ env.PLAN_PATH }}`

            - Fügt/gewährleistet Smoke-Test für `scripts/normalize_leads.py`
            - Idempotent, nur Ergänzungen

            Closes #${{ env.ISSUE_NUMBER }} (falls Issue dieses Deliverable explizit fordert)
          labels: agent:engineer, ready-for-review
          signoff: true
          delete-branch: true
