name: eval
on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch: {}

permissions:
  contents: read
  statuses: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --quiet pytest
      - name: Run unit tests
        run: |
          pytest -q
      - name: Run smoke eval script
        run: |
          python scripts/check_eval.py
      - name: Set commit status 'eval'
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const state = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            const description = state === 'success' ? 'Smoke passed' : 'Smoke failed';
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state,
              context: 'eval',
              description,
              target_url: `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            });

