name: Orchestrator

on:
  issues: { types: [opened, labeled, edited, reopened] }
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue
              ? `#${context.payload.issue.number}`
              : `(manual)`;
            core.info(`ORCH PING for issue ${issue} @ ${new Date().toISOString()}`);
