name: Orchestrator
on:
  issues: { types: [opened, labeled, edited, reopened] }
  workflow_dispatch: {}
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ORCH PING ${{ github.event_name }} #${{ github.event.issue.number || '' }}"
