name: orchestrate
on:
  issues:
    types: [opened, labeled, edited]

jobs:
  plan_and_delegate:
    # nur laufen, wenn Label task:agent vorhanden ist oder gerade gesetzt wurde
    if: >
      (github.event.action == 'labeled' && github.event.label.name == 'task:agent') ||
      contains(toJson(github.event.issue.labels), 'task:agent')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Installiere nur, wenn requirements.txt existiert
      - name: Install dependencies
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run orchestrator
        run: python scripts/orchestrate.py
