name: Orchestrator
on:
  issues:
    types: [labeled]
concurrency:
  group: orchestrate-${{ github.event.issue.number }}
  cancel-in-progress: false
permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write
jobs:
  orchestrate:
    if: ${{ github.event.label.name == 'task:agent' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run orchestrator
        id: orch
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python scripts/orchestrate.py
      - name: Commit plan files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/board/ || true
          git commit -m "chore(plan): add/update plan for #${{ github.event.issue.number }}" || echo "No changes"
          git push || true
      - name: Comment plan link on issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const planPath = process.env.PLAN_PATH || "(kein Plan gefunden)";
            const body = `Plan erzeugt/aktualisiert: \`${planPath}\``;
            await github.rest.issues.createComment({ ...context.repo, issue_number, body });
        env:
          PLAN_PATH: ${{ steps.orch.outputs.plan_path }}
      - name: Trigger agents (repo_dispatch + workflow_dispatch fallback)
        uses: actions/github-script@v7
        env:
          PLAN_PATH: ${{ steps.orch.outputs.plan_path }}
        with:
          script: |
            const {owner, repo} = context.repo;
            const issue = context.payload.issue;
            const title = (issue.title || "").toLowerCase();
            const ref   = context.payload.repository?.default_branch || "main";
            const wantsEngineer = /(parse|script|normalize|gate|test|engineer|pipeline)/.test(title);
            const wantsGrowth   = /(outreach|draft|growth|message|email|template)/.test(title);
            const payloadBase = {
              issue_number: issue.number,
              plan_path: process.env.PLAN_PATH || "",
              issue_title: issue.title || ""
            };
            async function fire(tag, wf) {
              try {
                await github.rest.repos.createDispatchEvent({ owner, repo, event_type: tag, client_payload: payloadBase });
                console.log(`repository_dispatch ${tag} OK`);
              } catch (e) {
                console.log(`repository_dispatch ${tag} failed: ${e.message}`);
              }
              try {
                await github.rest.actions.createWorkflowDispatch({ owner, repo, workflow_id: wf, ref,
                  inputs: { issue_number: String(issue.number), plan_path: payloadBase.plan_path, issue_title: payloadBase.issue_title }});
                console.log(`workflow_dispatch ${wf} OK`);
              } catch (e) {
                console.log(`workflow_dispatch ${wf} failed: ${e.message}`);
              }
            }
            if (wantsEngineer) await fire("agent-engineer", "agent-engineer.yml");
            if (wantsGrowth)   await fire("agent-growth",   "agent-growth.yml");
