name: release
on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --quiet pytest
      - name: Run unit tests
        run: |
          pytest -q
      - name: Run smoke eval script
        run: |
          python scripts/check_eval.py
  deploy_staging:
    needs: eval
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to staging
        run: |
          echo "Deploying to staging... (no-op for static site)"
  deploy_prod:
    needs: deploy_staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to production
        run: |
          echo "Deploying to production after HITL approval..."
