name: Secret Scan (soft)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.py'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.go'
      - '**/*.java'
      - '.github/workflows/**'
  workflow_dispatch: {}
permissions:
  contents: read
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: gitleaks (soft)
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64.tar.gz \
            | tar -xz || true
          ./gitleaks detect --no-git -v || echo "::warning::gitleaks found issues (soft)"

