name: secret-scan
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Secret scanning with trufflehog
        uses: trufflesecurity/trufflehog@v3
        with:
          path: .
          extra_args: --only-verified