name: Secret Scan (soft)
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: gitleaks (soft)
        run: |
          set -e
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64.tar.gz \
            | tar -xz && ./gitleaks detect --no-git -v || echo "::warning::gitleaks found issues (soft)"
